drivers: qca-wifi-host-cmn: Fix error cause a function declaration is deprecated
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/umac/scan/dispatcher/src/wlan_extscan_api.c:103:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
wlan_extscan_global_deinit()
                          ^
                           void
1 error generated.